#import = [
#    "~/.config/alacritty/themes/themes/dark_plus.toml",
#]

[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"

[general]
live_config_reload = true
import = [
    "~/.config/alacritty/github_light_high_contrast.toml",
]

[font.normal]
family = "Iosevka Nerd Font Mono"
